import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import DynamicMap from "./DynamicMap";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        {/* leaflet */}
        <link href={'https://cdn.jsdelivr.net/npm/leaflet.locatecontrol/dist/L.Control.Locate.min.css'}
              rel={'stylesheet'}/>
        <script
          async={true}
          charSet='utf-8'
          type="text/javascript"
          src={'https://cdn.jsdelivr.net/npm/leaflet.locatecontrol/dist/L.Control.Locate.min.js'}
        />

        <link
          rel={'stylesheet'}
          crossOrigin=''
          href={'https://unpkg.com/leaflet@1.8.0/dist/leaflet.css'}
          integrity='sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=='
        />
        <script
          async={true}
          crossOrigin=''
          integrity='sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=='
          src={'https://unpkg.com/leaflet@1.8.0/dist/leaflet.js'}
        />
        <script
          async={true}
          src={'https://raw.githubusercontent.com/pa7/heatmap.js/develop/plugins/leaflet-heatmap/leaflet-heatmap.js'}
        />
        {/* leaflet */}

        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href={"/favicon.ico"}/>
      </Head>
      <main className={styles.main}>
        {<DynamicMap/>}
      </main>
      <footer className={styles.footer}>
        footer
      </footer>
    </div>

  )
}

export default Home
